options(repos = c(CRAN = "https://cloud.r-project.org"))
options(java.parameters = "-Xmx6G")
library(data.table)
library(sf)
library(r5r)
repo_dir <- "C:/Users/fjanatab/Downloads/daedal-map-main/daedal-map-main"
network_dir <- file.path(repo_dir, "static", "data", "r5r_lake_network")
cat('START_SETUP\n')
r5 <- setup_r5(data_path = network_dir, verbose = FALSE)
cat('SETUP_DONE\n')
origins_sf <- st_read(file.path(repo_dir, "static", "data", "tiger2020_lake_county_tracts_nri.geojson"), quiet = TRUE)
origins_sf <- st_transform(origins_sf, 4326)
origins_pts <- st_point_on_surface(origins_sf)
origins <- data.table(id = as.character(origins_pts$GEOID), lon = st_coordinates(origins_pts)[,1], lat = st_coordinates(origins_pts)[,2])

shelters_sf <- st_read(file.path(repo_dir, "static", "data", "nss_lake_county_facilities.geojson"), quiet = TRUE)
shelters_sf <- st_transform(shelters_sf, 4326)
shelters <- data.table(id = as.character(shelters_sf$shelter_id), lon = st_coordinates(shelters_sf)[,1], lat = st_coordinates(shelters_sf)[,2], opportunities = 1)

cat('RUN_ACCESS\n')
acc <- accessibility(r5r_core = r5, origins = origins[1:3], destinations = shelters[1:10], mode='CAR', opportunities_colname='opportunities', cutoffs=30, progress=FALSE, verbose=TRUE)
cat('ACCESS_DONE_ROWS', nrow(acc), '\n')
print(head(acc))
stop_r5(r5)
cat('DONE\n')
